### PR TITLE
replaces react-emotion with @emotion/styled

### PR DESCRIPTION
**Pull request by loremipson**
These are the changes I needed to make for #6. A couple of things to note on:

1. [Updated `package.json` version to `1.0.0`](https://github.com/JoshRosenstein/emotion-icons/compare/master...loremipson:master#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R3) as this will break if the user isn't using emotion 10. This may not follow the versioning that you have in mind, feel free to change or suggest otherwise.
2. I'm not sure _why_, but I had to [specify `px` on the `width`/`height`](https://github.com/JoshRosenstein/emotion-icons/compare/master...loremipson:master#diff-3546d1abbf0b8815d42e9cd0a3cc5631R39) for it to work like this. This may not be where you want this applied?

### CODE REVIEW

**Comment by JoshRosenstein** [comment]
Thanks for contributing, everything looks good to me, and and versioning is fine. In regards to specifying px. [Emotion adds px to numbers](https://github.com/emotion-js/emotion/blob/86700d21ccd8bcc6fc2740c5d6b381dfe8a9bce1/packages/serialize/src/index.js#L49) so im not sure where you are having issues. Also, icon packages like Ion dont have a default height/width, so that will return 'undefinedpx' for height and width.

Heres a sandbox to play with:
[Edit Emotion Icons- pull 7](https://codesandbox.io/s/3xmprzy8o6)

If im missing something can you please provide a sandbox where you were having issues with the units?
thanks

**Comment by loremipson** [comment]
Interesting. I ran into it when using Material with Emotion 10. It works with 8/9. But material sizes are coming back as a string, and it looks like that's why.

https://codesandbox.io/s/5w3j76p76l

When you pass `<Done />` by itself, or if you pass `size`/`width` as a string ("32") then it doesn't get applied.

With that being the case, and with some of them not having sizes, it'll probably be better if we just parseInt the value? I'll see if that still works as expected.

**Comment by JoshRosenstein** [comment]
Aw yes, good find. should change the source files of Boxicons, SimpleIcons, and material to have numbers instead of strings and material width being `parseInt(match[4]) || 24`

**Comment by JoshRosenstein** [comment]
Source files meaning: https://github.com/JoshRosenstein/emotion-icons/blob/pr/7/scripts/sources.

If you want to make those changes in your fork, i will merge and release.

**Comment by loremipson** [comment]
Okay, that's updated. I'm having some weird issues on the docz side of things. It looks like some styles aren't coming through when I render them on my side? Still tracking that down, or I would have included the updates there too.

**Comment by loremipson** [comment]
Hmm, looks like the docz might need to stick to emotion 9 for now: pedronauck/docz#486

**Comment by JoshRosenstein** [comment]
I'll look into the docz issue, but i guess this is the downside of trying to integrate/simplify the documentation within the same package. For now I think i will merge these changes in, and if i cant get the docz to work, i'll pull it out separately and push out V1.0

**Pull request merged**
